### ISSUE TITLE
Some guides on modifying layout would be very useful

### ISSUE THREAD

**Issue by ntaylor-barnett** [ma-ha/easy-web-gui#11]
I'm starting to ramp up my efforts in using this and it is working to provide a UI my restful functions which is great! The problem I'm starting to hit is that it is getting confusing understanding how the layout works so i can get it looking a bit nicer. An example of what I am trying to achieve is this:

> I have a page with two views: a form and a table. I have successfully got it working so that the form queries an API, gets the results and shows it. Problem is that the view is very restrictive and i want it so that the entire view enlarges to fit the contents (so the page scrolls rather than the smaller view). It seems I am stuck with fixed pixel sizing. My attempts to do things like setting the "height" of the table to 100% does now work as while I can see this directive in the css class correctly, it gets overidden by a specific "style" that is being applied to the object that sets the height to something like 22px and i cannot find a way to override this behaviour.

It would be great if you could provide some more detailed guides on how to adjust the layouts with various examples. I'm sure there are ways I could hack the CSS to get it to behave the way I need it to, but I am intentionally trying to avoid mucking around with UI stuff so I can just write the functions I need and get on with my day.

**Comment by ma-ha** [comment]
Hi Nathan, is this for mobile/tablet or PC browser? For PC the % makes 
IMHO no sense, since you don’t know what the height is. I’m currently on 
vacation, but I’ll send you a working as soon as possible.
Greetings, Markus



Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm>

-----Original-Nachricht-----
Von: Nathan Taylor-Barnett <notifications@github.com
<mailto:notifications@github.com> >
Betreff: [ma-ha/easy-web-app] Some guides on modifying layout would be very 
useful (#11)
Datum: 14.10.2020, 04:57 Uhr
An: ma-ha/easy-web-app <easy-web-app@noreply.github.com
<mailto:easy-web-app@noreply.github.com> >
CC: Subscribed <subscribed@noreply.github.com
<mailto:subscribed@noreply.github.com> >

I'm starting to ramp up my efforts in using this and it is working to 
provide a UI my restful functions which is great! The problem I'm starting 
to hit is that it is getting confusing understanding how the layout works 
so i can get it looking a bit nicer. An example of what I am trying to 
achieve is this:

    I have a page with two views: a form and a table. I have successfully
    got it working so that the form queries an API, gets the results and
    shows it. Problem is that the view is very restrictive and i want it so
    that the entire view enlarges to fit the contents (so the page scrolls
    rather than the smaller view). It seems I am stuck with fixed pixel
    sizing. My attempts to do things like setting the "height" of the table
    to 100% does now work as while I can see this directive in the css
    class correctly, it gets overidden by a specific "style" that is being
    applied to the object that sets the height to something like 22px and i
    cannot find a way to override this behaviour.

It would be great if you could provide some more detailed guides on how to 
adjust the layouts with various examples. I'm sure there are ways I could 
hack the CSS to get it to behave the way I need it to, but I am 
intentionally trying to avoid mucking around with UI stuff so I can just 
write the functions I need and get on with my day.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ma-ha/easy-web-app/issues/11> , or unsubscribe

**Comment by ma-ha** [comment]
Hi, 
a % height does not make sense in all cases. Instead I added a "height"="auto" option for this. 
Pls update to newest version 2.9.4 and test if that's what you need.  
Greetings, Markus

**Comment by ma-ha** [comment]
... see [example](https://github.com/ma-ha/easy-web-app/tree/master/examples/table-demo)
index-auto.js vs index.js
